language: c
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - TESTS=false
    matrix:
        - OCAML_VERSION=4.09 EXTRA_DEPS="solo5-bindings-hvt"
        - OCAML_VERSION=4.09 EXTRA_DEPS="solo5-bindings-spt"
        - OCAML_VERSION=4.09 EXTRA_DEPS="solo5-bindings-virtio"
        - OCAML_VERSION=4.09 EXTRA_DEPS="solo5-bindings-muen"
        - OCAML_VERSION=4.09 EXTRA_DEPS="solo5-bindings-genode"
        - OCAML_VERSION=4.08 EXTRA_DEPS="solo5-bindings-hvt"
        - OCAML_VERSION=4.07 EXTRA_DEPS="solo5-bindings-hvt"
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-bindings-hvt"
        - OCAML_VERSION=4.05 EXTRA_DEPS="solo5-bindings-hvt"
